"""initial MangoLab schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_access',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gpu_budget_mib', sa.Integer(), server_default=sa.text('4096'), nullable=False),
    sa.Column('cpu_quota_pct', sa.Integer(), server_default=sa.text('200'), nullable=False),
    sa.Column('mem_max_mb', sa.Integer(), server_default=sa.text('6144'), nullable=False),
    sa.Column('disk_quota_mb', sa.Integer(), server_default=sa.text('20480'), nullable=False),
    sa.Column('max_runtimes', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('idle_timeout_min', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('granted_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='mangolab'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('workspace_path', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_projects_owner_id'), 'projects', ['owner_id'], unique=False, schema='mangolab')
    op.create_table('notebooks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kernel_name', sa.Text(), server_default='python3', nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('etag', sa.Text(), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_saved_by', sa.Text(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mangolab.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_notebooks_project_id'), 'notebooks', ['project_id'], unique=False, schema='mangolab')
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='viewer', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['mangolab.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    schema='mangolab'
    )
    op.create_table('runtimes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='starting', nullable=False),
    sa.Column('driver', sa.Text(), server_default='systemd-user', nullable=False),
    sa.Column('unit_name', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('gpu_budget_mib', sa.Integer(), nullable=False),
    sa.Column('cpu_quota_pct', sa.Integer(), nullable=False),
    sa.Column('mem_max_mb', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['mangolab.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_runtimes_owner_id'), 'runtimes', ['owner_id'], unique=False, schema='mangolab')
    op.create_index(op.f('ix_mangolab_runtimes_project_id'), 'runtimes', ['project_id'], unique=False, schema='mangolab')
    op.create_table('ai_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('notebook_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), server_default='New conversation', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['mangolab.notebooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['mangolab.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_ai_threads_project_id'), 'ai_threads', ['project_id'], unique=False, schema='mangolab')
    op.create_index(op.f('ix_mangolab_ai_threads_user_id'), 'ai_threads', ['user_id'], unique=False, schema='mangolab')
    op.create_table('kernel_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=True),
    sa.Column('kernel_id', sa.Text(), nullable=False),
    sa.Column('kernel_name', sa.Text(), server_default='python3', nullable=False),
    sa.Column('status', sa.Text(), server_default='starting', nullable=False),
    sa.Column('execution_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['mangolab.notebooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['runtime_id'], ['mangolab.runtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_kernel_sessions_runtime_id'), 'kernel_sessions', ['runtime_id'], unique=False, schema='mangolab')
    op.create_table('notebook_revisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['mangolab.notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_notebook_revisions_notebook_id'), 'notebook_revisions', ['notebook_id'], unique=False, schema='mangolab')
    op.create_table('package_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('specs', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['runtime_id'], ['mangolab.runtimes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_package_jobs_user_id'), 'package_jobs', ['user_id'], unique=False, schema='mangolab')
    op.create_table('resource_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_pct', sa.Double(), nullable=True),
    sa.Column('ram_mb', sa.Integer(), nullable=True),
    sa.Column('gpu_mem_mib', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['runtime_id'], ['mangolab.runtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index('ix_resource_samples_runtime_ts', 'resource_samples', ['runtime_id', 'ts'], unique=False, schema='mangolab')
    op.create_table('terminals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('runtime_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runtime_id'], ['mangolab.runtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_terminals_runtime_id'), 'terminals', ['runtime_id'], unique=False, schema='mangolab')
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['mangolab.ai_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_ai_messages_thread_id'), 'ai_messages', ['thread_id'], unique=False, schema='mangolab')
    op.create_table('executions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('notebook_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('cell_id', sa.Text(), nullable=False),
    sa.Column('msg_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error_name', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['mangolab.notebooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['mangolab.kernel_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['public.User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_executions_notebook_id'), 'executions', ['notebook_id'], unique=False, schema='mangolab')
    op.create_index(op.f('ix_mangolab_executions_session_id'), 'executions', ['session_id'], unique=False, schema='mangolab')
    op.create_index(op.f('ix_mangolab_executions_user_id'), 'executions', ['user_id'], unique=False, schema='mangolab')
    op.create_table('ai_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='proposed', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['mangolab.ai_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mangolab'
    )
    op.create_index(op.f('ix_mangolab_ai_actions_message_id'), 'ai_actions', ['message_id'], unique=False, schema='mangolab')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mangolab_ai_actions_message_id'), table_name='ai_actions', schema='mangolab')
    op.drop_table('ai_actions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_executions_user_id'), table_name='executions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_executions_session_id'), table_name='executions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_executions_notebook_id'), table_name='executions', schema='mangolab')
    op.drop_table('executions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_ai_messages_thread_id'), table_name='ai_messages', schema='mangolab')
    op.drop_table('ai_messages', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_terminals_runtime_id'), table_name='terminals', schema='mangolab')
    op.drop_table('terminals', schema='mangolab')
    op.drop_index('ix_resource_samples_runtime_ts', table_name='resource_samples', schema='mangolab')
    op.drop_table('resource_samples', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_package_jobs_user_id'), table_name='package_jobs', schema='mangolab')
    op.drop_table('package_jobs', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_notebook_revisions_notebook_id'), table_name='notebook_revisions', schema='mangolab')
    op.drop_table('notebook_revisions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_kernel_sessions_runtime_id'), table_name='kernel_sessions', schema='mangolab')
    op.drop_table('kernel_sessions', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_ai_threads_user_id'), table_name='ai_threads', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_ai_threads_project_id'), table_name='ai_threads', schema='mangolab')
    op.drop_table('ai_threads', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_runtimes_project_id'), table_name='runtimes', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_runtimes_owner_id'), table_name='runtimes', schema='mangolab')
    op.drop_table('runtimes', schema='mangolab')
    op.drop_table('project_members', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_notebooks_project_id'), table_name='notebooks', schema='mangolab')
    op.drop_table('notebooks', schema='mangolab')
    op.drop_index(op.f('ix_mangolab_projects_owner_id'), table_name='projects', schema='mangolab')
    op.drop_table('projects', schema='mangolab')
    op.drop_table('lab_access', schema='mangolab')
    # ### end Alembic commands ###
